### ISSUE TITLE
Latest image doesn't works anymore with error at startup : "/bin/sh: [tailon,: not found"

### ISSUE THREAD

**Issue by rzteux** [port22/tailon#1]
All is in the title ...

**Comment by rzteux** [comment]
And to avoid miss update issue, is it possible to tag your releases with versions ?
Regards.

**Comment by port22** [comment]
Somehow the arg-separated syntax is bugged. I changed the Entrypoint to CMD in simple syntax.

Releases are now tagged as versions.
Current release: `port22/tailon:0.2`

cheers
